Repository 3-talking-potatoes/coins-never-die, pull requests merged in 2023-01, with the labels that each got.

#11 #8 💰 feat : 리액트 쿼리 세팅
  .github/ISSUE_TEMPLATE/📈-cnd-issue-template.md
  .vscode/settings.json
  README.md
  src/app/layout.tsx
  src/app/page.tsx
Labels: 🐰 한승호, ⛲ Feature

#13 #10 💰 feat : 회원가입 페이지 구현
  .gitignore
  package-lock.json
  package.json
  src/Firebase.ts
  src/app/sign-up/page.tsx
Labels: 🐣 최유정, ⛲ Feature, 👽️ API

#15 #9 :gem: style: tailwind color custom
  tailwind.config.js
Labels: 🖼 HTML&CSS, 🐳 이채은

#16 #9 :gem: style: tailwind color custom 블랙 수정
  tailwind.config.js
Labels: 🖼 HTML&CSS, 🐳 이채은

#17 #9 :gem: style: 폰트 수정
  src/app/globals.css
  src/app/layout.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#18 #9 :gem: style: 매수 컴포넌트 디자인 완료
  src/app/buy/page.tsx
  tailwind.config.js
Labels: 🖼 HTML&CSS, 🐳 이채은
