Repository 3-talking-potatoes/coins-never-die, pull requests merged in 2023-02, with the labels that each got.

#20 #12 💳 api: 빗썸 api 통신 기능 구현, axios 설치
  package-lock.json
  package.json
  src/api/getCoinData.ts
  src/api/getCoinList.ts
  src/app/globals.css
  src/app/page.tsx
  src/atoms/atom.tsx
  src/components/Search.tsx
  src/interface/interface.ts
Labels: 🐰 한승호, 👽️ API

#22 #19 :gem: style: 보유자산 스타일 구현
  package-lock.json
  package.json
  src/app/buy/page.tsx
  src/app/components/MyAssets.tsx
  src/app/components/Trading.tsx
  tailwind.config.js
Labels: 🖼 HTML&CSS, 🐳 이채은

#23 #21 💰 feat: 검색 기능 구현
  src/app/buy/[...coins]/page.tsx
  src/app/page.tsx
  src/atoms/atom.tsx
  src/components/Search.tsx
Labels: 🐰 한승호, ⛲ Feature

#24 #14 💰 feat : 로그인 페이지 구현
  src/Firebase.ts
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
  src/atoms/atom.tsx
Labels: 🐣 최유정, ⛲ Feature, 👽️ API

#26 #19 :gem: style: 보유자산 코인 디테일 스타일 완료
  src/app/components/MyAssets.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#28 #21 💰 feat: 검색 컴포넌트 구현
  src/app/page.tsx
  src/atoms/atom.tsx
  src/components/Search.tsx
Labels: 🐰 한승호, ⛲ Feature

#29 #21 💰 feat: 검색 기능 구현
  src/app/page.tsx
  src/components/CoinList.tsx
Labels: 🐰 한승호, ⛲ Feature

#31 #27 💰 feat: url에 쿼리 추가
  src/app/buy/page.tsx
  src/components/CoinList.tsx
  src/components/MyAssets.tsx
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#32 #27 💰 feat: 코인 한글 이름 및 현재가 불러오기 구현
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#33 #25 💰 feat : 유저 자산 데이터베이스 연동 기능 구현
  package-lock.json
  package.json
  src/Firebase.ts
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
Labels: 🐣 최유정, ⛲ Feature, 👽️ API

#34 #27 💵 fix: 가격, 수량, 총액 계산 오류 해결
  src/atoms/atom.tsx
  src/components/Trading.tsx
Labels: 🚨 BugFix, 🐳 이채은, ⛲ Feature

#35 #27 💰 feat: 비율에 따른 주문 총액, 주문 수량 계산 기능 구현 및 초기화 기능 구현
  src/atoms/atom.tsx
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#37 #25 💎 style : login, signup 페이지 css
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
Labels: 🖼 HTML&CSS, 🐣 최유정

#38 #30 💰 feat: 검색 컴포넌트 화살표키 탐색 구현
  src/atoms/atom.tsx
  src/components/CoinList.tsx
  src/components/Search.tsx
  src/interface/interface.ts
Labels: 🐰 한승호, ⛲ Feature

#40 #25 💰 feat : 유저 자산 데이터베이스 연동 기능 구현
  src/atoms/atom.tsx
  src/hooks/getUserData.ts
Labels: 🐣 최유정, ⛲ Feature, 👽️ API

#41 #36 💵 fix: useeffect 무한루프로 인한 가격계산 오류 수정
  src/atoms/atom.tsx
  src/components/Trading.tsx
Labels: 🚨 BugFix, 🐳 이채은

#42 #36 💵 fix: 버튼 클릭에 따른 주문수량 계산 오류 수정
  src/components/Trading.tsx
Labels: 🚨 BugFix, 🐳 이채은

#43 #25 💰 feat : 데이터 업데이트 함수 구현
  src/hooks/updateUserData.ts
Labels: 🐣 최유정, ⛲ Feature, 👽️ API

#44 #36 💰 feat: 주문수량 소수점 8자리 표시
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#46 #25 💵 fix : atom 새로고침시 로그인 유지
  package-lock.json
  package.json
  src/atoms/atom.tsx
Labels: 🚨 BugFix, 🐣 최유정

#47 #45 💰 feat: 매수기능 구현
  src/atoms/atom.tsx
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#48 #45 #25 💵 fix : 업데이트 함수 합산 가능하게 수정
  src/components/LogInOutButton.tsx
  src/components/Trading.tsx
  src/hooks/updateUserData.ts
Labels: 🚨 BugFix, ⛲ Feature

#49 #45 💰 feat: 매수기능 수정
  src/atoms/atom.tsx
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#50 #25 💰 feat : logInOut, logo 컴포넌트 생성
  src/components/Logo.tsx
  src/hooks/getUserData.ts
Labels: ⛲ Feature

#53 #39 💷 refactor : 메인페이지 관련 컴포넌트 리팩토링
  .cspell.json
  src/api/getCoinData.ts
  src/api/getCoinList.ts
  src/atoms/atom.tsx
  src/components/CoinList.tsx
  src/components/Search.tsx
  src/hooks/useCoinList.ts
  src/hooks/useSearch.ts
Labels: 🐰 한승호, ⛲ Feature

#55 #52 💰 feat: 보유자산 서버연동
  src/app/buy/page.tsx
  src/components/MyAssets.tsx
  src/components/Trading.tsx
Labels: 🐳 이채은, ⛲ Feature

#57 #51 💰 feat : db ts타입설정
  src/atoms/atom.tsx
  src/interface/interface.ts
Labels: 🐣 최유정, ⛲ Feature

#58 #54 💵 fix : 타입스크립트 오류 해결 및 기타 오류 해결
  src/hooks/useCoinList.ts
  src/hooks/useSearch.ts
  src/interface/interface.ts
Labels: 🚨 BugFix, 🐰 한승호

#60 #51 💰 feat : 유효성검사, 에러 알림창, 컴포넌트 분리1
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/LogInForm.tsx
  src/components/SignUpForm.tsx
  src/hooks/useAuthorization.ts
  tailwind.config.js
Labels: 🐣 최유정, ⛲ Feature

#62 #59 💎 style : CSS 수정 및 반응형 구현
  src/app/page.tsx
  src/atoms/atom.tsx
  src/components/CoinList.tsx
  src/components/PageArrowKey.tsx
  src/components/Search.tsx
  src/hooks/useCoinList.ts
  src/hooks/useSearch.ts
Labels: 🖼 HTML&CSS, 🐰 한승호

#63 #56 💰 feat: 보유자산 항목 계산
  src/app/buy/page.tsx
  src/atoms/atom.tsx
  src/components/MyAsset/MyAssetCoinList.tsx
  src/components/MyAsset/MyAssets.tsx
  src/components/Trading.tsx
  src/interface/interface.ts
Labels: 🐳 이채은, ⛲ Feature

#64 #61 💵 fix : catch 에러 처리 타입 오류 수정
  src/components/LogInForm.tsx
  src/components/SignUpForm.tsx
  src/hooks/useAuthorization.ts
Labels: 🚨 BugFix, 🐣 최유정

#66 #56 💷 refactor: utils 폴더 생성 및 주석 제거
  src/atoms/atom.tsx
  src/components/MyAsset/MyAssetCoinList.tsx
  src/components/Trading.tsx
  src/utils/NumberFormat.ts
Labels: 🐳 이채은, 🔧refactor

#68 #67 💎 style: 보유자산 코인리스트 css 수정
  src/atoms/atom.tsx
  src/components/MyAsset/MyAssetCoinList.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#69 #67 💎 style: 보유자산 코인리스트 css 수정
  package-lock.json
  package.json
  src/atoms/atom.tsx
  src/components/MyAsset/MyAssetCoinList.tsx
  src/components/MyAsset/MyAssets.tsx
  tailwind.config.js
Labels: 🖼 HTML&CSS, 🐳 이채은

#72 #71 💷 refactor: 커스텀 hooks 및 파일 위치 변경
  src/app/exchange/page.tsx
  src/app/log-in/page.tsx
  src/app/page.tsx
  src/app/sign-up/page.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
  src/components/exchange/Trading.tsx
  src/components/log-in/LogInForm.tsx
  src/components/log-in/LogInOutButton.tsx
  src/components/main/CoinList.tsx
  src/components/main/PageArrowKey.tsx
  src/components/main/Search.tsx
  src/components/sign-up/SignUpForm.tsx
  src/hooks/useTrading.ts
Labels: 🐳 이채은, 🔧refactor

#73 #71 💷 refactor: useExchange 커스텀 hooks 생성
  src/app/exchange/page.tsx
  src/hooks/useExchange.ts
Labels: 🐳 이채은, 🔧refactor

#75 #70 💎 style : 컴포넌트 스타일 수정
  src/app/exchange/page.tsx
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/Logo.tsx
  src/components/log-in/LogInOutButton.tsx
Labels: 🖼 HTML&CSS, 🐣 최유정

#76 #74 💵 fix: 평가손익 계산 오류 수정
  src/app/exchange/page.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
Labels: 🚨 BugFix, 🐳 이채은

#79 #65 💵 fix: css 수정 및 타입스크립트 오류 수정 및 검색 기능 수정
  src/app/page.tsx
  src/components/exchange/MyAssets.tsx
  src/components/main/CoinList.tsx
  src/components/main/PageArrowKey.tsx
  src/components/main/Search.tsx
Labels: 🖼 HTML&CSS, 🐰 한승호, ⛲ Feature

#80 #78 💷 refactor : logIn 리팩터링
  src/components/log-in/EmailLogInForm.tsx
  src/components/log-in/LogInForm.tsx
  src/components/log-in/SocialLogInButton.tsx
  src/components/sign-up/SignUpForm.tsx
  src/hooks/useLogInForm.ts
  src/utils/logIn&SignUp/createUserWithEmail.ts
  src/utils/logIn&SignUp/isSignUp.ts
  src/utils/logIn&SignUp/logInWithEmail.ts
  src/utils/logIn&SignUp/setUserData.ts
  src/utils/logIn&SignUp/useAuthorization.ts
  src/utils/useSocialLogInProvider.ts
Labels: 🐣 최유정, 🔧refactor

#82 #65 💵 fix: css 수정 및 타입스크립트 오류 수정 및 검색 기능 수정
  src/components/exchange/MyAssets.tsx
  src/components/main/CoinList.tsx
  src/components/main/Search.tsx
  src/hooks/useSearch.ts
Labels: 🚨 BugFix, 🖼 HTML&CSS, 🐰 한승호

#84 #83 💎 style : CSS 반응형 수정
  src/app/page.tsx
  src/components/main/CoinList.tsx
  src/components/main/PageArrowKey.tsx
Labels: 🖼 HTML&CSS, 🐰 한승호

#86 #77 💰 feat: 매도기능 구현
  src/atoms/atom.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/Trading.tsx
  src/hooks/useTrading.ts
Labels: ⛲ Feature

#87 #85 💷 refactor : 로그아웃 알림창 추가, 리팩토링
  src/app/page.tsx
  src/atoms/atom.tsx
  src/components/log-in/LogInOutButton.tsx
  src/components/main/CoinList.tsx
  src/hooks/useCoinList.ts
  src/hooks/useSearch.ts
Labels: 🐰 한승호, 🔧refactor

#88 #74 💎 style : 메인페이지 css 수정
  src/app/page.tsx
  src/components/main/CoinList.tsx
  src/hooks/useCoinList.ts
Labels: 🖼 HTML&CSS, 🐳 이채은

#89 #81 💷 refactor : 회원가입 페이지 리팩터링
  src/components/log-in/EmailLogInForm.tsx
  src/components/log-in/LogInForm.tsx
  src/components/log-in/SocialLogInButton.tsx
  src/components/sign-up/SignUpForm.tsx
  src/components/sign-up/SignUpFormInput.tsx
  src/components/sign-up/useSignUpForm.tsx
  src/hooks/useSocialLogInProvider.ts
Labels: 🚨 BugFix, 🖼 HTML&CSS, 🐣 최유정, 🔧refactor

#91 #90 💵 fix: 매수시 버튼 클릭 안되는 오류 수정
  src/hooks/useTrading.ts
Labels: 🚨 BugFix, 🐳 이채은

#92 #90 💵 fix: 매도시 주문총액, 주문수량 Nan 오류 수정
  src/hooks/useTrading.ts
Labels: 🚨 BugFix, 🐳 이채은

#94 #93 💵 fix : 렌더링 오류 수정
  src/components/exchange/MyAssets.tsx
  src/hooks/useTrading.ts
Labels: 🚨 BugFix, 🐰 한승호

#95 #90 💵 fix: 매매페이지 오류 수정
  src/app/exchange/page.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/hooks/useExchange.ts
  src/hooks/useInterval.ts
  src/hooks/useTrading.ts
  src/interface/interface.ts
Labels: 🚨 BugFix, 🐳 이채은

#96 #81 💵 fix : 타입스크립트 오류 수정
  src/atoms/atom.tsx
  src/hooks/useTrading.ts
  src/interface/interface.ts
Labels: 🚨 BugFix, 🐣 최유정, 🐳 이채은, 🐰 한승호

#97 #90 💵 fix: 매매페이지 오류 수정
  src/components/exchange/MyAssetCoinList.tsx
  src/hooks/useTrading.ts
  src/interface/interface.ts
Labels: 🚨 BugFix, 🐳 이채은

#99 #98 💵 fix: package.json 수정
  package.json
Labels: 🚨 BugFix, 🐰 한승호

#101 #100 💵 fix : eslint,prettier 에러 수정
  .vscode/settings.json
  package-lock.json
  src/app/exchange/page.tsx
  src/app/head.tsx
  src/app/page.tsx
  src/atoms/atom.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
  src/components/sign-up/SignUpFormInput.tsx
  src/components/sign-up/useSignUpForm.tsx
  src/hooks/getUserData.ts
  src/hooks/updateUserData.ts
  src/hooks/useCoinList.ts
  src/hooks/useExchange.ts
  src/hooks/useInterval.ts
  src/hooks/useLogInForm.ts
  src/hooks/useSearch.ts
  src/hooks/useTrading.ts
  src/pages/api/hello.ts
  src/utils/NumberFormat.ts
  src/utils/logIn&SignUp/logInWithEmail.ts
Labels: 🚨 BugFix, 🐣 최유정, 🐳 이채은, 🐰 한승호

#102 #90 💵 fix: 업데이트 시간 변경
  src/components/exchange/MyAssetCoinList.tsx
  src/hooks/useExchange.ts
Labels: 🚨 BugFix, 🐳 이채은

#105 #103 💎 style : 매매페이지 반응형 css
  src/app/exchange/page.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
  src/components/exchange/Trading.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#106 #104 💎 style : 메인페이지 반응형 CSS 수정
  src/app/head.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/main/CoinList.tsx
Labels: 🖼 HTML&CSS, 🐰 한승호

#109 #107 💎 style : css 수정
  src/atoms/atom.tsx
  src/components/main/CoinList.tsx
  src/hooks/useCoinList.ts
Labels: 🖼 HTML&CSS, 🐰 한승호

#110 #90 💵 fix: 매매페이지 오류 수정
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
  src/components/log-in/LogInOutButton.tsx
  src/hooks/useTrading.ts
Labels: 🚨 BugFix, 🐳 이채은

#112 #111 💵 fix : 메인 페이지 기능 수정
  src/components/main/CoinList.tsx
  src/hooks/useCoinList.tsx
Labels: 🚨 BugFix, 🖼 HTML&CSS, 🐰 한승호

#116 #113 💎 style : 다크모드 적용
  src/app/exchange/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/log-in/page.tsx
  src/app/page.tsx
  src/app/sign-up/page.tsx
  src/components/Logo.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
  src/components/exchange/Trading.tsx
  src/components/log-in/EmailLogInForm.tsx
  src/components/log-in/LogInForm.tsx
  src/components/log-in/LogInOutButton.tsx
  src/components/log-in/SocialLogInButton.tsx
  src/components/main/CoinList.tsx
  src/components/main/PageArrowKey.tsx
  src/components/main/Search.tsx
  src/components/sign-up/SignUpForm.tsx
  src/components/sign-up/SignUpFormInput.tsx
  src/components/sign-up/useSignUpForm.tsx
  tailwind.config.js
Labels: 🖼 HTML&CSS, 🐰 한승호

#117 #114 💎 style : login 페이지, signup 페이지 높이 조절, 아이콘 추가
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/Logo.tsx
  src/components/log-in/LogInForm.tsx
  src/components/sign-up/SignUpForm.tsx
Labels: 🖼 HTML&CSS, 🐣 최유정

#118 #114 💎 style : login 페이지, signup 페이지 높이 조절, 아이콘 추가
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/Trading.tsx
  src/hooks/useExchange.ts
  src/hooks/useTrading.ts
  src/utils/NumberFormat.ts
Labels: 🖼 HTML&CSS, 🐣 최유정

#120 #114 💎 style : 스크롤바 제거
  src/components/log-in/LogInForm.tsx
  src/components/sign-up/SignUpForm.tsx
Labels: 🖼 HTML&CSS, 🐣 최유정

#121 #103 💎 style : 보유자산 css 수정
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/MyAssets.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#122 #114 💎 style : 로그인, 회원가입 높이 조절
  src/app/log-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/log-in/EmailLogInForm.tsx
  src/components/log-in/LogInForm.tsx
  src/components/sign-up/SignUpForm.tsx
  src/components/sign-up/SignUpFormInput.tsx
  src/components/sign-up/useSignUpForm.tsx
Labels: 🖼 HTML&CSS, 🐣 최유정

#124 #123 💵 fix : 로그인 후 매수 매도 페이지 undefined 에러 수정
  src/utils/logIn&SignUp/useAuthorization.ts
Labels: 🚨 BugFix, 🐣 최유정

#128 #127 💷 refactor: 매매페이지 리팩터링
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/Trading.tsx
  src/hooks/useMyAssetCoinList.ts
  src/hooks/useTrading.ts
Labels: 🐳 이채은, 🔧refactor

#130 #129 💵 fix: 소수점 오류 수정
  src/hooks/useTrading.ts
Labels: 🚨 BugFix, 🐳 이채은

#131 #129 💷 refactor: 콘솔 제거
  src/hooks/useTrading.ts
Labels: 🐳 이채은, 🔧refactor

#133 💎 style: 코인이모티콘 추가
  src/app/exchange/page.tsx
  src/components/exchange/Trading.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#135 #132 💎 style: 평가손익, 수익률에 따른 글자색 변경
  src/components/exchange/MyAssetCoinList.tsx
Labels: 🖼 HTML&CSS, 🐳 이채은

#136 #136 👛 merge: 브랜치 병합
  src/app/exchange/page.tsx
  src/components/exchange/MyAssetCoinList.tsx
  src/components/exchange/Trading.tsx
  src/hooks/useMyAssetCoinList.ts
  src/hooks/useTrading.ts
Labels: 🐳 이채은, 📲 merge

#138 #137 🏦 db : 회원 초기 cash 변경
  src/utils/logIn&SignUp/useAuthorization.ts
Labels: 🐣 최유정, 🗃️ DB

#139 #139 👛 merge : dev에서 main으로 병합
  src/utils/logIn&SignUp/useAuthorization.ts
Labels: 🐣 최유정, 📲 merge

#140 💷 refactor : 트레이딩 컴포넌트 리팩터링
  src/hooks/useTrading.ts
Labels: 🐳 이채은, 🔧refactor

#141 #134 💵 fix : 100% 매수 오류 수정
  src/hooks/useTrading.ts
Labels: 🚨 BugFix, 🐳 이채은

#143 #142 💎 style : 메인페이지 모바일 반응형 css 구현
  src/components/main/CoinList.tsx
  src/components/main/Search.tsx
Labels: 🖼 HTML&CSS, 🐰 한승호

#145 #144 💎 style : 로그인, 회원가입 페이지 반응형
  README.md
  src/components/log-in/EmailLogInForm.tsx
  src/components/log-in/LogInForm.tsx
  src/components/sign-up/SignUpForm.tsx
  src/components/sign-up/SignUpFormInput.tsx
  src/components/sign-up/useSignUpForm.tsx
Labels: 🖼 HTML&CSS, 🐣 최유정
